services:
  - type: web
    name: beleqet-backend
    runtime: node
    plan: free
    rootDirectory: backend
    buildCommand: npm install && npm run build && npm run prisma:generate
    startCommand: npm run prisma:migrate && npm run prisma:seed && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: beleqet-db
          property: connectionString
      - key: REDIS_HOST
        value: "none" # Set to 'none' to prevent crashing if you don't have Redis
      - key: JWT_ACCESS_SECRET
        value: secure_production_random_secret_string_here
      - key: BULL_BOARD_USERNAME
        value: admin
      - key: BULL_BOARD_PASSWORD
        value: admin

databases:
  - name: beleqet-db
    plan: free